* conflict with lilo until the next regular maintainer upload, this is a   pity, but required due to the following reasons:   - unconfigured lilo installations are dangerous on upgrades, #504376.   - it is broken in combination with a default initramfs-tools setup,     #479607.   - grub does not allow bootloader coexistance on the system.   - lilo is unlikely to be part of squeeze, cf.     http://lists.debian.org/debian-devel/2008/06/msg00400.html * sync with Debian svn r1109:   - update-grub: Try to regenerate device.map when grub-probe fails (and     inform the user about it).  Thanks Raphaël Hertzog.  (Closes: #501306).

diff --git a/debian/update-grub b/debian/update-grub
--- a/debian/update-grub
+++ b/debian/update-grub
@@ -152,7 +152,17 @@ convert () {
 	if ! test -e ${device_map} ; then
 		echo quit | grub --batch --no-floppy --device-map=${device_map} > /dev/null
 	fi
-	GRUB_LEGACY_0_BASED_PARTITIONS=1 grub-probe --device-map=${device_map} -t drive -d "$1" 2> /dev/null
+	GRUB_LEGACY_0_BASED_PARTITIONS=1 grub-probe --device-map=${device_map} -t drive -d "$1" 2> /dev/null || { 
+		echo "warning: grub-probe can't find drive for $1." >&2
+		tmp_map=$(mktemp -t device.map.XXXXXXXX)
+		grub-mkdevicemap --device-map=${tmp_map} --no-floppy >/dev/null 2>&1 || true
+		GRUB_LEGACY_0_BASED_PARTITIONS=1 grub-probe --device-map=${tmp_map} -t drive -d "$1" || {
+			rm -f ${tmp_map}
+			return 1
+		}
+		echo "Please check ${device_map}, you might have to regenerate it with grub-mkdevicemap." >&2
+		rm -f ${tmp_map}
+	}
 }
 
 # Usage: convert_default os_device
@@ -214,7 +224,7 @@ title="Debian GNU/`uname -s | sed -e s,GNU/,,g`"
 updatedefaultentry="false"
 
 # Drive(in GRUB terms) where the kernel is located. Overridden by the
-# kopt statement in menufile.
+# groot statement in menufile.
 grub_root_device=$(convert_default "$boot_device")
 
 # should grub create the alternative boot options in the menu
