* drop use_grub-probe_in_grub-install.diff and revert modifications for   update-grub from 0.97-33, the changes to grub-install don't work with   --root-directory yet.

diff --git a/debian/update-grub b/debian/update-grub
--- a/debian/update-grub
+++ b/debian/update-grub
@@ -59,7 +59,46 @@ find_grub_dir ()
 
 find_device ()
 {
-	grub-probe -t device $1
+	mount_point=$1
+
+	# Autodetect current root device
+	device=
+	if [ -f /etc/fstab ] ; then
+		while read DEV MNT FOO; do
+			if `echo "$DEV" | grep -q "^#"`; then
+				continue
+			fi
+			if [ "$MNT" = "$mount_point" ]; then
+				device="$DEV";
+			fi
+		done < /etc/fstab
+	fi
+
+	if [ -n "$device" ] ; then
+		case "$device" in
+			LABEL=* | UUID=*)
+				device=`readlink -f "$(findfs $device)"`
+			;;
+			*)
+				device=`readlink -f "$device"`
+			;;
+		esac
+	fi
+
+	echo $device
+}
+
+find_root_device ()
+{
+	device=$(find_device "/")
+
+	if [ -z "$device" ]; then
+		echo "Cannot determine root device.  Assuming /dev/hda1" >&2
+		echo "This error is probably caused by an invalid /etc/fstab" >&2
+		device=/dev/hda1
+	fi
+
+	echo $device
 }
 
 # Usage: convert_raid1 os_device
@@ -92,12 +131,115 @@ convert_raid1 ()
 
 # Usage: convert os_device
 # Convert an OS device to the corresponding GRUB drive.
+# This part is OS-specific.
 convert () {
-    GRUB_LEGACY_0_BASED_PARTITIONS=1 grub-probe -t drive -d "$1"
+    # First, check if the device file exists.
+    if test -e "$1"; then
+		:
+    else
+		echo "$1: Not found or not a block device." 1>&2
+		exit 1
+    fi
+
+	host_os=`uname -s | tr '[[:upper:]]' '[[:lower:]]'`
+
+    # Break the device name into the disk part and the partition part.
+    case "$host_os" in
+    linux)
+		tmp_disk=`echo "$1" | sed -e 's%\([sh]d[[:lower:]]\)[0-9]*$%\1%' \
+				  -e 's%\(fd[0-9]*\)$%\1%' \
+				  -e 's%/part[0-9]*$%/disc%' \
+				  -e 's%\(c[0-7]d[0-9]*\).*$%\1%'`
+		tmp_part=`echo "$1" | sed -e 's%.*/[sh]d[[:lower:]]\([0-9]*\)$%\1%' \
+				  -e 's%.*/fd[0-9]*$%%' \
+				  -e 's%.*/floppy/[0-9]*$%%' \
+				  -e 's%.*/\(disc\|part\([0-9]*\)\)$%\2%' \
+				  -e 's%.*c[0-7]d[0-9]*p*%%'`
+	;;
+    gnu)
+		tmp_disk=`echo "$1" | sed 's%\([sh]d[0-9]*\).*%\1%'`
+		tmp_part=`echo "$1" | sed "s%$tmp_disk%%"` ;;
+    freebsd|*/kfreebsd)
+		tmp_disk=`echo "$1" | sed 's%r\{0,1\}\([saw]d[0-9]*\).*$%\1%' \
+			    | sed 's%r\{0,1\}\(da[0-9]*\).*$%\1%'`
+		tmp_part=`echo "$1" \
+	    		| sed "s%.*/r\{0,1\}[saw]d[0-9]\(s[0-9]*[a-h]\)%\1%" \
+       	    	| sed "s%.*/r\{0,1\}da[0-9]\(s[0-9]*[a-h]\)%\1%"`
+	;;
+    netbsd|*/knetbsd)
+		tmp_disk=`echo "$1" | sed 's%r\{0,1\}\([sw]d[0-9]*\).*$%r\1d%' \
+	    		| sed 's%r\{0,1\}\(fd[0-9]*\).*$%r\1a%'`
+		tmp_part=`echo "$1" \
+	    		| sed "s%.*/r\{0,1\}[sw]d[0-9]\([abe-p]\)%\1%"`
+	;;
+    *)
+		echo "update-grub does not support your OS yet." 1>&2
+		exit 1 ;;
+    esac
+
+    # Get the drive name.
+    tmp_drive=`grep -v '^#' $device_map | grep "$tmp_disk *$" \
+			| sed 's%.*\(([hf]d[0-9][a-z0-9,]*)\).*%\1%'`
+
+    # If not found, print an error message and exit.
+    if test "x$tmp_drive" = x; then
+		echo "$1 does not have any corresponding BIOS drive." 1>&2
+		exit 1
+    fi
+
+    if test "x$tmp_part" != x; then
+		# If a partition is specified, we need to translate it into the
+		# GRUB's syntax.
+		case "$host_os" in
+		linux)
+	    	  echo "$tmp_drive" | sed "s%)$%,`expr $tmp_part - 1`)%" ;;
+		gnu)
+	    	  if echo $tmp_part | grep "^s" >/dev/null; then
+				tmp_pc_slice=`echo $tmp_part \
+		    		| sed "s%s\([0-9]*\)[a-z]*$%\1%"`
+				tmp_drive=`echo "$tmp_drive" \
+		    		| sed "s%)%,\`expr "$tmp_pc_slice" - 1\`)%"`
+	    	  fi
+	    	  if echo $tmp_part | grep "[a-z]$" >/dev/null; then
+				tmp_bsd_partition=`echo "$tmp_part" \
+		    		| sed "s%[^a-z]*\([a-z]\)$%\1%"`
+				tmp_drive=`echo "$tmp_drive" \
+		    		| sed "s%)%,$tmp_bsd_partition)%"`
+	    	  fi
+	    	  echo "$tmp_drive" ;;
+		freebsd|*/kfreebsd)
+	    	  if echo $tmp_part | grep "^s" >/dev/null; then
+				tmp_pc_slice=`echo $tmp_part \
+		    		| sed "s%s\([0-9]*\)[a-h]*$%\1%"`
+				tmp_drive=`echo "$tmp_drive" \
+		    		| sed "s%)%,\`expr "$tmp_pc_slice" - 1\`)%"`
+	    	  fi
+	    	  if echo $tmp_part | grep "[a-h]$" >/dev/null; then
+				tmp_bsd_partition=`echo "$tmp_part" \
+		    		| sed "s%s\{0,1\}[0-9]*\([a-h]\)$%\1%"`
+				tmp_drive=`echo "$tmp_drive" \
+		    		| sed "s%)%,$tmp_bsd_partition)%"`
+	    	  fi
+	    	  echo "$tmp_drive" ;;
+		netbsd|*/knetbsd)
+	    	  if echo $tmp_part | grep "^[abe-p]$" >/dev/null; then
+				tmp_bsd_partition=`echo "$tmp_part" \
+		    		| sed "s%\([a-p]\)$%\1%"`
+				tmp_drive=`echo "$tmp_drive" \
+		    		| sed "s%)%,$tmp_bsd_partition)%"`
+	    	  fi
+	    	  echo "$tmp_drive" ;;
+		esac
+    else
+		# If no partition is specified, just print the drive name.
+		echo "$tmp_drive"
+    fi
 }
 
 # Usage: convert_default os_device
 # Convert an OS device to the corresponding GRUB drive.
+# Calls OS-specific convert, and returns a default of
+# (hd0,0) if anything goes wrong
 convert_default () {
 	# Check if device is software raid1 array
 	if tmp_dev=$(convert_raid1 $1 2>/dev/null) ; then
@@ -106,7 +248,11 @@ convert_default () {
 		tmp_dev=$1
 	fi
 
-	convert $tmp_dev
+	if tmp=$(convert $tmp_dev 2>/dev/null) ; then
+		echo $tmp
+	else
+		echo "(hd0,0)"
+	fi
 }
 
 ## Configuration Options
@@ -125,16 +271,10 @@ default_file_basename=default
 default_file=$grub_dir/$default_file_basename
 
 # the device for the / filesystem
-root_device=$(find_device "/")
+root_device=$(find_root_device)
 
 # the device for the /boot filesystem
 boot_device=$(find_device "/boot")
-
-# figure out where grub looks for the kernels at boot time
-kernel_dir=/boot
-if [ "$boot_device" != "$root_device" ] ; then
-	kernel_dir=
-fi
 
 # Full path to the device.map
 device_map=$grub_dir/device.map
@@ -152,7 +292,11 @@ updatedefaultentry="false"
 # kopt statement in menufile.
 # if we don't have a device.map then we can't use the convert function.
 if test -f "$device_map" ; then
-	grub_root_device=$(convert_default "$boot_device")
+	if test -z "$boot_device" ; then
+		grub_root_device=$(convert_default "$root_device")
+	else
+		grub_root_device=$(convert_default "$boot_device")
+	fi
 else
 	grub_root_device="(hd0,0)"
 fi
@@ -719,7 +863,7 @@ echo >> $buffer
 
 echo -n "Searching for splash image ... " >&2
 current_splash=`grep '^splashimage=' ${menu_file} || true`
-splashimage_path="splashimage=${grub_root_device}${grub_dir##${kernel_dir}}/splash.xpm.gz"
+splashimage_path="splashimage=${grub_root_device}${grub_dir##${boot_device:+/boot}}/splash.xpm.gz"
 if [ `sed -e "/^$start/,/^$end/d" $menu_file | grep -c '^splashimage='` != "0" ] ; then
        #checks for splashscreen defined outside the autoupdated part
        splashimage=$(grep '^splashimage=' ${menu_file})
@@ -815,6 +959,12 @@ for hyp in /boot/xen-*.gz; do
     fi
 done
 
+# figure out where grub looks for the kernels at boot time
+kernel_dir=/boot
+if [ -n "$boot_device" ] ; then
+	kernel_dir=
+fi
+
 #Finding the value the default line
 use_grub_set_default="false"
 if test "$updatedefaultentry" = "true" ; then
@@ -850,9 +1000,9 @@ esac
 ## heres where we start writing out the kernel entries
 counter=0
 
-grub2name="${grub_dir##${kernel_dir}}/core.img"
 if [ "$LET_US_TRY_GRUB_2" = "true" ] \
-  && test -f $grub2name ; then
+  && test -f /boot/grub/core.img ; then
+	grub2name="$kernel_dir/grub/core.img"
 	echo "Found GRUB 2: $grub2name" >&2
 	cat >> $buffer << EOF
 title		Chainload into GRUB 2
